### ISSUE TITLE
Unable to import piquasso(5.0.0) on Windows OS

### ISSUE THREAD

**Issue by Hugh-888** [Budapest-Quantum-Computing-Group/piquasso#389]
### Environment

- **Python version**: 3.10
- **Piquasso version**:  5.0.0
- **Operating system**: Windows

### What is the error?

Unable to import piquasso on Windows OS since the file piquasso._math.torontonian is missing
![img_v3_02gc_dd4a4804-57f1-4920-a2ec-d5343757d89g](https://github.com/user-attachments/assets/7cb2f0fd-3be8-42b3-95e2-d18cd5178f4c)

### Steps to reproduce the problem

import piquasso

### What should happen?

ModuleNotFoundError: No module named 'piquasso._math.torontonian'

**Comment by Kolarovszki** [comment]
Hi! Thank you for raising an issue.

This error must be a Windows-specific packaging issue, I will try to solve this ASAP and release a patch.

Until then, maybe you could try uninstalling and reinstalling from source distribution:
```
pip uninstall piquasso
pip install --no-binary=:all: piquasso==5.0.0
```
I hope this helps.

**Comment by Kolarovszki** [comment]
Or, if you are satisfied with the previous version, you can try with
```
pip install piquasso==4.0.0
```

**Comment by Hugh-888** [comment]
Hi, thanks for the quick reply, currently using  piquasso 4.0.0 is fine
